Repository itc-21-25/3itcTeamGame, pull requests merged in 2023-10, with the labels that each got.

#8 feat: added custom workflow
  .github/workflows/label_project_addition.yml
Labels: Code Review, feature

#10 Update README.md
  README.md
Labels: Code Review

#11 management/change/readmeAndTestWorkflow
  .github/workflows/test.yml
  README.md
Labels: MERGE EXPERT

#12 management/feature/editOfProjectBuilder
  .github/workflows/build.yml
Labels: feature, Build

#16 management/update/mergeBranchFromMain
  .github/files/import.bat
  .github/files/readme-gif.gif
  README.md
Labels: MERGE EXPERT, update
