Repository itc-21-25/3itcTeamGame, pull requests merged in 2023-12, with the labels that each got.

#101 GWLD/feature/96-gamerplayDocs
  Beyblade_Hra_dokumentace_v1.2.md
Labels: Code Review, Feature

#110 3D-MODELING/feature/NO-ID/addedObjects
  Assets/Graphics/Objects/bayblade/obranybb.fbx
  Assets/Graphics/Objects/bayblade/staminabb.fbx
  Assets/Graphics/Objects/bayblade/utocnybb.fbx
  Assets/Graphics/Objects/maps/Map1.fbx
  Assets/Graphics/Objects/maps/Map2.fbx
  Assets/Graphics/Objects/maps/Map3.fbx
  Assets/Graphics/Objects/maps/Tribunes.fbx
Labels: 3D MODELING, Spojovani

#109 PRG2/feature/22+102+54+55+103+52+53+51
  .gitignore
  Assets/3itcTeamGame.unity
  Assets/3itcTeamGame.unity.meta
  Assets/GreyScripts/LevelManager.cs
  Assets/GreyScripts/LevelManager.cs.meta
  Assets/GreyScripts/ModeSelect.cs
  Assets/GreyScripts/ModeSelect.cs.meta
  Assets/GreyScripts/Movement.cs
  Assets/GulagScripts.meta
  Assets/GulagScripts/AudioManager.cs
  Assets/GulagScripts/AudioManager.cs.meta
  Assets/HuricanScripts.meta
  Assets/HuricanScripts/BeyBladeClass.cs
  Assets/HuricanScripts/BeyBladeClass.cs.meta
  Assets/HuricanScripts/BeybladeSelector.cs
  Assets/HuricanScripts/BeybladeSelector.cs.meta
  Assets/KubaScripts.meta
  Assets/KubaScripts/PlayerCashManager.meta
  Assets/KubaScripts/PlayerCashManager/CashManager.cs
  Assets/KubaScripts/PlayerCashManager/CashManager.cs.meta
  Assets/KubaScripts/PlayerManager.cs
  Assets/KubaScripts/PlayerManager.cs.meta
  Assets/Scenes/AudioManager.unity
  Assets/Scenes/AudioManager.unity.meta
  Packages/manifest.json
  Packages/packages-lock.json
  UpgradeLog.htm
Labels: PRG 2, Spojovani
